# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 12:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('nick', models.CharField(max_length=200)),
                ('real_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('A', 'Activo'), ('R', 'Reserva'), ('N', 'Novato')], max_length=1)),
                ('played', models.IntegerField(blank=True)),
                ('picture', models.FileField(blank=True, upload_to='media')),
                ('add_date', models.DateTimeField(verbose_name='date registered')),
                ('mod_date', models.DateTimeField(verbose_name='date modified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
