# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('award_type', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('C', 'Mencion'), ('M', 'Medalla')], max_length=1)),
                ('picture', models.FileField(blank=True, upload_to='media/awards')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(verbose_name='date awarded')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='users.Award')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('rank', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('picture', models.FileField(blank=True, upload_to='media/units')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='member',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='mod_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AddField(
            model_name='member',
            name='rank',
            field=models.CharField(choices=[('SL', 'Soldado'), ('SR', 'Sargento'), ('CA', 'Capitan'), ('CO', 'Comandante')], default='Soldado', max_length=2),
        ),
        migrations.AddField(
            model_name='unit',
            name='members',
            field=models.ManyToManyField(through='users.MemberUnit', to='users.Member'),
        ),
        migrations.AddField(
            model_name='memberunit',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.Member'),
        ),
        migrations.AddField(
            model_name='memberunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='users.Unit'),
        ),
        migrations.AddField(
            model_name='memberaward',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded', to='users.Member'),
        ),
        migrations.AddField(
            model_name='award',
            name='awarded',
            field=models.ManyToManyField(through='users.MemberAward', to='users.Member'),
        ),
        migrations.AddField(
            model_name='member',
            name='awards',
            field=models.ManyToManyField(through='users.MemberAward', to='users.Award'),
        ),
        migrations.AddField(
            model_name='member',
            name='units',
            field=models.ManyToManyField(through='users.MemberUnit', to='users.Unit'),
        ),
    ]
